"""create_voice_profile

Revision ID: 00fb7cb0addb
Revises: f2fe16dba3cc
Create Date: 2026-08-05 01:48:49.798793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fb7cb0addb'
down_revision: Union[str, Sequence[str], None] = 'f2fe16dba3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_profiles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('supported_languages', sa.Text(), nullable=False),
    sa.Column('voice_provider', sa.String(length=50), nullable=False),
    sa.Column('voice_configuration', sa.Text(), nullable=True),
    sa.Column('preview_audio', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_profiles')
    # ### end Alembic commands ###
